import type { TicketBunny } from "../shared/ticket-bunny";

export const bunnyAccessoryGroups = [
  "Drinks & treats",
  "Ribbons & hair clips",
  "Hats & headwear",
  "Ear jewellery & necklaces",
  "Glasses & tech",
  "Bags & little treasures",
] as const;

export const bunnyAccessoryDetails = {
  bow: { label: "Ribbon", group: "Ribbons & hair clips" },
  leopardbow: { label: "Leopard bow", group: "Ribbons & hair clips" },
  flower: { label: "Hibiscus", group: "Ribbons & hair clips" },
  tiara: { label: "Tiara", group: "Hats & headwear" },
  headphones: { label: "Headphones", group: "Glasses & tech" },
  heartshades: { label: "Heart shades", group: "Glasses & tech" },
  hoops: { label: "Gold ear hoops", group: "Ear jewellery & necklaces" },
  flipphone: { label: "Deco flip phone", group: "Glasses & tech" },
  chain: { label: "Gold chain", group: "Ear jewellery & necklaces" },
  monster: { label: "Monster energy can", group: "Drinks & treats" },
  redbull: { label: "Red Bull can", group: "Drinks & treats" },
  strawberrysoda: { label: "Strawberry soda", group: "Drinks & treats" },
  bubbletea: { label: "Bubble tea", group: "Drinks & treats" },
  icedmatcha: { label: "Iced matcha", group: "Drinks & treats" },
  coffeecup: { label: "Coffee cup", group: "Drinks & treats" },
  ramune: { label: "Ramune bottle", group: "Drinks & treats" },
  juicebox: { label: "Carrot juice box", group: "Drinks & treats" },
  milkcarton: { label: "Strawberry milk", group: "Drinks & treats" },
  lollipop: { label: "Swirl lollipop", group: "Drinks & treats" },
  icecream: { label: "Double-scoop ice cream", group: "Drinks & treats" },
  donut: { label: "Glazed doughnut", group: "Drinks & treats" },
  cupcake: { label: "Cherry cupcake", group: "Drinks & treats" },
  cherryclip: { label: "Cherry clip", group: "Ribbons & hair clips" },
  starclip: { label: "Star barrette", group: "Ribbons & hair clips" },
  butterflyclip: { label: "Butterfly clip", group: "Ribbons & hair clips" },
  daisyclips: { label: "Daisy clips", group: "Ribbons & hair clips" },
  pearlclips: { label: "Pearl barrettes", group: "Ribbons & hair clips" },
  ribbonbraids: { label: "Twin trailing ribbons", group: "Ribbons & hair clips" },
  scrunchie: { label: "Ruffled ear scrunchie", group: "Ribbons & hair clips" },
  lacebonnet: { label: "Lace bonnet", group: "Hats & headwear" },
  beret: { label: "Heart beret", group: "Hats & headwear" },
  buckethat: { label: "Daisy bucket hat", group: "Hats & headwear" },
  beanie: { label: "Pom-pom beanie", group: "Hats & headwear" },
  sailorhat: { label: "Sailor cap", group: "Hats & headwear" },
  heartdrops: { label: "Heart ear drops", group: "Ear jewellery & necklaces" },
  stardrops: { label: "Star ear drops", group: "Ear jewellery & necklaces" },
  cherrydrops: { label: "Cherry ear drops", group: "Ear jewellery & necklaces" },
  pearlstuds: { label: "Pearl ear studs", group: "Ear jewellery & necklaces" },
  earcuffs: { label: "Triple ear cuffs", group: "Ear jewellery & necklaces" },
  safetypins: { label: "Safety-pin earrings", group: "Ear jewellery & necklaces" },
  choker: { label: "Heart choker", group: "Ear jewellery & necklaces" },
  locket: { label: "Heart locket", group: "Ear jewellery & necklaces" },
  roundglasses: { label: "Round gold glasses", group: "Glasses & tech" },
  catglasses: { label: "Cat-eye glasses", group: "Glasses & tech" },
  starshades: { label: "Star sunglasses", group: "Glasses & tech" },
  pixelshades: { label: "Pixel shades", group: "Glasses & tech" },
  camera: { label: "Digital camera", group: "Glasses & tech" },
  gameconsole: { label: "Pocket game console", group: "Glasses & tech" },
  handbag: { label: "Quilted handbag", group: "Bags & little treasures" },
  leopardbag: { label: "Leopard shoulder bag", group: "Bags & little treasures" },
  heartbag: { label: "Heart purse", group: "Bags & little treasures" },
  teddy: { label: "Teddy bear", group: "Bags & little treasures" },
  bunnyplush: { label: "Tiny bunny plush", group: "Bags & little treasures" },
  carrotplush: { label: "Carrot plush", group: "Bags & little treasures" },
  heartwand: { label: "Heart wand", group: "Bags & little treasures" },
  starwand: { label: "Star wand", group: "Bags & little treasures" },
  moonwand: { label: "Moon wand", group: "Bags & little treasures" },
  sakura: { label: "Sakura sprig", group: "Bags & little treasures" },
  fan: { label: "Ribbon folding fan", group: "Bags & little treasures" },
  umbrella: { label: "Lace parasol", group: "Bags & little treasures" },
} satisfies Record<
  TicketBunny["accessory"],
  { label: string; group: (typeof bunnyAccessoryGroups)[number] }
>;
